---
- name: download nginx source
  get_url: url=http://nginx.org/download/nginx-{{ ngx_ver }}.tar.gz
           dest=/tmp/nginx-{{ ngx_ver }}.tar.gz

- name: download lua nginx module
  get_url: url=https://github.com/chaoslawful/lua-nginx-module/archive/v{{ lua_ngx_ver }}.tar.gz
           dest=/tmp/lua-nginx-module-{{ lua_ngx_ver }}.tar.gz

- name: extract nginx source
  command: tar zxvf nginx-{{ ngx_ver }}.tar.gz chdir=/tmp

- name: rename nginx directory
  command: mv nginx-{{ ngx_ver }} nginx chdir=/tmp

- name: extract lua nginx module source
  command: tar zxvf lua-nginx-module-{{ lua_ngx_ver }}.tar.gz chdir=/tmp

- name: rename lua nginx module directory
  command: mv lua-nginx-module-{{ lua_ngx_ver }} lua-nginx-module chdir=/tmp

- name: copy build script
  copy: src=build-nginx.sh dest=/tmp/nginx/build-nginx.sh mode=0755

- name: build nginx
  command: ./build-nginx.sh chdir=/tmp/nginx

- name: copy geoip data file
  copy: src=GeoIP.dat dest={{ ngx_conf_path }}/GeoIP.dat

- name: deploy nginx config
  template: src={{ ngx_role }}/nginx.conf.j2 dest={{ ngx_conf_path }}/nginx.conf
  tags:
    - ngx_conf

- name: create vhost.d directory
  file: path={{ ngx_conf_path }}/vhost.d state=directory
  tags:
    - ngx_mkdir

- name: deploy nginx vhosts
  template: src={{ item }} dest={{ ngx_conf_path }}/vhost.d/
  with_fileglob:
    - ../templates/{{ ngx_role }}/vhost.d/*
  tags:
    - ngx_vhost
