#!/usr/bin/env perl

use strict;
use warnings;
use YAML;
use Getopt::Long;

my $name  = '';
my $hosts = '';
my $user  = '';
my @roles = ();

GetOptions(
    'name=s'  => \$name,
    'hosts=s' => \$hosts,
    'user=s'  => \$user,
    'roles=s' => \@roles,
);

my $array;
if ( $name && $hosts && $user && @roles ) {
    @roles = split( /,/, join( ',', @roles ) );
    my $hash = {
        name  => $name,
        hosts => $hosts,
        user  => $user,
        roles => [@roles],
    };
    YAML::Bless($hash)->keys( [qw(name hosts user roles)] );
    push @$array, $hash;
}
else {
    die "Usage: $0 -n <name> -h <hosts> -u <user> -r <role,role,role...>\n";
}

YAML::DumpFile( 'temp.yml', $array );
