---
- name: bootstrap server
  hosts: bootstrap
  user: root
  gather_facts: True

  roles:
    - epel
    - packages
    - sudo
    - ssh
    - limits
    - selinux
    - users
    - nginx
    - squid
    - ansible
    - rsync
