---
- name: download squid source
  get_url: url=http://linuxtoy.org/files/squid-{{ squid_version }}.lekan-modified.tar.gz
           dest=/tmp/squid-{{ squid_version }}.lekan-modified.tar.gz

- name: extract squid source
  command: tar zxvf squid-{{ squid_version }}.lekan-modified.tar.gz chdir=/tmp

- name: rename squid directory
  command: mv squid-{{ squid_version }}.lekan-modified squid chdir=/tmp

- name: copy build script
  copy: src=build-squid.sh dest=/tmp/squid/build-squid.sh mode=0755

- name: build squid
  command: ./build-squid.sh chdir=/tmp/squid

- name: deploy squid config
  template: src=squid.conf.j2 dest={{ squid_conf_path }}/squid.conf
  tags:
    - squid_config
